import { it, expect } from "vitest";
import { parseGcode } from "../src/gcode.js";
const code = `; generated by BambuStudio\n; model printing time: 1h 2m 3s; total estimated time: 1h 5m 3s\n; filament used [mm] = 1000, 2000\n; filament used [cm3] = 2.4, 4.8\n; filament used [g] = 3, 6\nG90\nM82\nG1 X10 Y10 Z0.2\n; CHANGE_LAYER\n; Z_HEIGHT: 0.2\n; LAYER_HEIGHT: 0.2\n; FEATURE: Outer wall\n; LINE_WIDTH: 0.42\nG1 X20 E1 F1200\nG1 E0.5\nG92 E0\nG1 Y20 E1\nG91\nM83\nG1 X-5 E0.3\nT1\nG1 Y-5 E0.2`;
it("keeps positions, relative modes, G92 and retractions consistent", () => {
  const p = parseGcode(code);
  const s = p.segments.filter((s) => s.extruding);
  expect(s).toHaveLength(4);
  expect(s[1].a).toEqual([20, 10, 0.2]);
  expect(s[2].b).toEqual([15, 20, 0.2]);
  expect(s[3].tool).toBe(1);
  expect(s[0].role).toBe("Outer wall");
  expect(s[0].width).toBe(0.42);
  expect(s[0].speed).toBe(20);
});
it("reads Bambu time and per filament units", () => {
  const stats = parseGcode(code).statistics;
  expect(stats.printSeconds).toBe(3723);
  expect(stats.totalSeconds).toBe(3903);
  expect(stats.weightG).toBe(9);
  expect(stats.filaments[1].lengthMm).toBe(2000);
});
it("does not invent missing statistics", () => {
  const p = parseGcode("G1 X1");
  expect(p.statistics.printSeconds).toBeNull();
  expect(p.statistics.weightG).toBeNull();
  expect(p.statistics.filaments).toEqual([]);
});
it("keeps physical coordinates continuous across G92 origin resets", () => {
  const p = parseGcode("G1 X10\nG92 X0\nG1 X1");
  expect(p.segments[1].a[0]).toBe(10);
  expect(p.segments[1].b[0]).toBe(11);
});
it("tessellates I/J arcs and preserves exact end point", () => {
  const p = parseGcode("G90\nM83\nG1 X10 Y0\nG3 X0 Y10 I-10 J0 E2");
  expect(p.segments.length).toBeGreaterThan(10);
  expect(p.segments.at(-1)?.b).toEqual([0, 10, 0]);
  for (const s of p.segments.slice(1))
    expect(Math.hypot(s.b[0], s.b[1])).toBeCloseTo(10, 4);
});
it("handles radius arcs and full circles", () => {
  const p = parseGcode("G1 X10\nG2 X0 Y10 R10\nG3 I0 J-10");
  expect(p.segments.at(-1)?.b).toEqual([0, 10, 0]);
  expect(p.segments.length).toBeGreaterThan(60);
});
it("warns on unsupported plane and never silently truncates geometry", () => {
  expect(parseGcode("G18\nG1 X1").warnings.join(" ")).toMatch(/G18/);
  expect(() => parseGcode("G1 X1\nG1 X2", 1)).toThrow(/límite/);
});
it("uses layer markers without treating z hops as layers", () => {
  const p = parseGcode(
    "; CHANGE_LAYER\n; Z_HEIGHT: 0.2\nG1 Z.2\nG1 X1 E1\nG1 Z.6\nG1 X2\nG1 Z.2\n; CHANGE_LAYER\n; Z_HEIGHT: 0.4\nG1 Z.4\nG1 X3 E2",
  );
  expect(p.layers.filter((l) => l.index > 0)).toHaveLength(2);
});
it("suppresses Bambu conditional calibration branches", () => {
  const p = parseGcode("M622 J1\nG1 X100 E1\nM623\nG1 X1 E1");
  expect(p.segments).toHaveLength(1);
  expect(p.warnings.join(" ")).toMatch(/condicional/);
});
it("reads the colon-delimited header emitted by Bambu Studio 02.08.02.61", () => {
  const s = parseGcode(
    "; BambuStudio 02.08.02.61\n; model printing time: 4m 51s; total estimated time: 11m 50s\n; total filament length [mm] : 694.76\n; total filament weight [g] : 2.11",
  ).statistics;
  expect(s.filaments[0]?.lengthMm).toBe(694.76);
  expect(s.weightG).toBe(2.11);
  expect(s.totalSeconds).toBe(710);
});
it("corrects the known 02.08.02.61 volume label from mm3 to cm3", () => {
  const p = parseGcode(
    "; BambuStudio 02.08.02.61\n; total filament volume [cm^3] : 1671.09",
  );
  expect(p.statistics.filaments[0].volumeCm3).toBeCloseTo(1.67109);
});

it("uses global relative mode for extrusion even with M82", () => {
  const p = parseGcode("M82\nG1 X1 E10\nG91\nG1 X1 E1");
  expect(p.segments[1].extruding).toBe(true);
});
